### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by zhaoxm469** [k8w/create-tsrpc-app#1]
您好 ，我想请问一下 您在开发这款工具时候 是如何调试的呢？ 

我把您的项目拉下来以后想打下断点进行调试

可是我没有看到您Script里没有把命令实时的把ts转换成js。不知您在开发过程中是如何处理的~

**Comment by k8w** [comment]
使用 ts-node
```
npm i ts-node
```

VSCode launch.json: 
```json
{
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "ts-node current file",
            "protocol": "inspector",
            "args": [
                "${relativeFile}"
            ],
            "cwd": "${workspaceRoot}",
            "runtimeArgs": [
                "-r",
                "ts-node/register"
            ],
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}
```

**Comment by zhaoxm469** [comment]
> 使用 ts-node
> 
> ```
> npm i ts-node
> ```
> 
> VSCode launch.json:
> 
> ```json
> {
>     "configurations": [
>         {
>             "type": "node",
>             "request": "launch",
>             "name": "ts-node current file",
>             "protocol": "inspector",
>             "args": [
>                 "${relativeFile}"
>             ],
>             "cwd": "${workspaceRoot}",
>             "runtimeArgs": [
>                 "-r",
>                 "ts-node/register"
>             ],
>             "internalConsoleOptions": "openOnSessionStart"
>         }
>     ]
> }
> ```

好的谢谢，万分感谢作者大大的回复~
